### ISSUE TITLE
New Matcher: .toBeNil()

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#7]
**Feature Request**

Description:

### .toBeNil()

Use `.toBeNil` when checking a value is null or undefined.

```js
test('passes when value is null or undefined', () => {
  expect(null).toBeNil();
  expect(undefined).toBeNil();
  expect(true).not.toBeNil();
});
```

**Comment by friscomm** [comment]
I'd like to give this a shot!

**Comment by mattphillips** [comment]
Hey @friscomm you got it! Don't forget to star ⭐️ and share the project 😄

**Comment by vikneshwar** [comment]
Hi, @mattphillips can I take this up if @friscomm is not working on this ?

**Comment by friscomm** [comment]
hey @vikneshwar I am giving it a go, but if I need some assistance I'd be down to reach out to you and we could pair on it?

**Comment by subinoy7** [comment]
Apologies as I didn't see that this is already taken. I was working on it as I wanted to learn.
@mattphillips I created a PR #96, and it took me whole day to learn that Travis CI was failing because I needed to add snapshot manually :smile: 

Though I am happy that I learned a lot, you can accept it or you can close it. It's up to you :smiley:

**Comment by mattphillips** [comment]
@friscomm I've merged @subinoy7 PR for now which closes this issue. @friscomm there are other APIs that I want to add to jest-extended and I would be happy to help you out if you wanted to add one just let me know :smile:
